#+TITLE: projects | alex bellon
#+OPTIONS: title:nil

#+HTML: <div id="projects" class="main">
#+HTML: <div class="contentBlock">

#+ATTR_HTML: :class comment
these are some of my personal projects. to see my research work check out my [[file:publications]]. to see /all/ my projects, visit my [[https://github.com/alex-bellon][github]], and check out my non-code projects on the [[file:misc]] page.

** [[https://github.com/utisss/][utctf (2019, 2020, 2021)]]
UTCTF is the international 48-hour CTF we ([[https://isss.io][ISSS]]) host every year. In 2021 and 2020 I led the project, coordinating the event planning, communication channels, prizes, etc. in addition to writing challenges for the CTF as part of my engineering officer duties. For UTCTF 2020 we had over *2500 users registered between 1300+ teams/*. In 2019 I wrote cryptography, forensics and miscellaneous challenges for the CTF.

** [[https://github.com/UTACM/CS101][cs101]]
As Web/Tech officer for UT's chapter of ACM, I created and hosted a series of workshops aimed at teaching freshmen technical skills that they are expected to know but aren't taught in class (e.g. Git, Linux, SSH, etc.). I wrote all of the curriculum and slides, did all of the marketing and hosted all of the events (until COVID hit).

** [[https://github.com/mozilla-services/dependency-observatory][dependency observatory]]
As part of my internship at Mozilla, I worked on the Dependency Observatory project. Dependency Observatory is a web service for collecting data about open source software dependencies (or package) and assessing how risky they are to use.

** [[https://github.com/alex-bellon/anshel-anshel-goldfeld-rubiks-cube][anshel-anshel-goldfeld key exchange]]
My implementation of the Anshel-Anshel-Goldfeld Key Exchange using the Rubiks's Cube group. I made this for one of my UTCTF 2020 problems.

** [[https://github.com/alex-bellon/ctf-challenges][ctf challenges]]
A collection of all of the CTF challenges I have written for ISSS's biweekly CTFs. I mainly write Forensics and Cryptography problems.

** [[https://github.com/alex-bellon/ctf-tools][ctf tools]]
Repository where I write tools to make and solve CTF challenges, as well as collect pre-existing tools.

** [[https://github.com/alex-bellon/cybersecurity-resources][cybersecurity resources]]
A collection of links, notes, programs, websites, etc. related to CTFs and cybersecurity.

** [[https://github.com/alex-bellon/drunken-bishop][drunken bishop]]
My Python implementation of the drunken bishop algorithm used to generate the ASCII art that you see when using OpenSSH. I made this for a CTF problem I wrote.

** [[https://forever.isss.io/][foreverCTF]]
An introductory and instructional CTF aimed at students new to cybersecurity, hosted by [[https://isss.io][ISSS]]. I wrote many of the forensics and cryptography problems.

** [[https://github.com/alex-bellon/quantum-money-attack][quantum money attack]]
This program was written as part of a CTF problem for UTCTF 2021 in which contestants had to recover the state of a piece of quantum money using a predefined set of gates.

** [[https://github.com/alex-bellon/rubikstega][rubikstega]]
My implementation of Rubikstega, a Rubik's cube based type of steganography. Whitepaper describing the algorithm can be found [[http://informatika.stei.itb.ac.id/~rinaldi.munir/TA/Makalah_TA_Ade_Yusuf.pdf][here]].

#+HTML: </div></div>
